# -*- coding: utf-8 -*-
"""WeatherForcastingApp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-Pz39uoJ87IBOxV_GVpCY_46Afms47_C

Import Libraries
"""

import requests
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.metrics import mean_squared_error
from datetime import datetime,timedelta
import pytz

API_KEY='8414dd804d65b13ee003e4f202cc57a6'
BASE_URL='https://api.openweathermap.org/data/2.5/'

"""Define Functions
1.Fetch Current Weather Data
"""

def get_current_weather(city):
  url=f"{BASE_URL}weather?q={city}&appid={API_KEY}&units=metric"
  response=requests.get(url)
  data=response.json()
  return {
      'city': data['name'],
      'current_temp': round(data['main']['temp']),
      'feels_like': round(data['main']['feels_like']),
      'temp_min': round(data['main']['temp_min']),
      'temp_max': round(data['main']['temp_max']),
      'humidity': round(data['main']['humidity']),
      'description': data['weather'][0]['description'],
      'country': data['sys']['country'],
      'wind_deg': data['wind']['deg'],
      'pressure': data['main']['pressure'],
      'Wind_Gust_Speed':data['wind']['speed'],

  }

"""2.Read Historical Data"""

def read_historical_data(filename):
  df=pd.read_csv(filename)
  df=df.dropna()
  df=df.drop_duplicates()
  return df

"""3.Prepare Data for training"""

def prepare_data(data):
  # Separate encoders for wind direction and rain label
  le_wind = LabelEncoder()
  le_rain = LabelEncoder()
  # Ensure WindGustDir is treated as a string before encoding to handle potential non-string types
  data['WindGustDir'] = data['WindGustDir'].astype(str)
  # Fit the encoder only on the unique values in the training data
  le_wind.fit(data['WindGustDir'].unique())
  data['WindGustDir'] = le_wind.transform(data['WindGustDir'])
  data['RainTomorrow'] = le_rain.fit_transform(data['RainTomorrow'])

  #define feature variable and target variable
  X=data[['MinTemp','MaxTemp','WindGustDir','WindGustSpeed','Humidity','Pressure','Temp']]#feature variable
  y=data[['RainTomorrow']]#target variable

  return X,y,le_wind

"""4.Train Rain Prediction Model"""

def train_rain_model(X,y):
  X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
  model=RandomForestClassifier(n_estimators=100,random_state=42)
  model.fit(X_train,y_train)

  y_pred=model.predict(X_test)
  print("Mean Square Error for Rain Model")
  print(mean_squared_error(y_test,y_pred))
  rmse = np.sqrt(mse) # Calculate RMSE
  r2 = r2_score(y_test, y_pred)
  mae = mean_absolute_error(y_test, y_pred)
  print("RMSE:", rmse)
  print("R2 Score:", r2)
  print("MAE:", mae)  
  return model

"""5.Prepare Regression Data"""

def prepare_regression_data(data,feature):
  x,y=[],[] #initalize lsit for feature and target value

  for i in range(len(data)-1):
    x.append(data[feature].iloc[i])

    y.append(data[feature].iloc[i+1])
  X=np.array(x).reshape(-1,1) # Fixed: use x instead of X and reshape correctly
  y=np.array(y)
  return X,y

"""6.Train Regression Model"""

def train_regression_model(X,y):
  model=RandomForestRegressor(n_estimators=100,random_state=42)
  model.fit(X,y)
  return model

"""7.Predict Future"""

def predict_future(model,current_value):
  predictions =[current_value]

  for i in range(5):
    next_value=model.predict(np.array([[predictions[-1]]]))
    predictions.append(next_value[0])
  return predictions[1:]

"""8.Weather Analysis Function"""

import pandas as pd
import pytz
from datetime import datetime, timedelta

def weather_view():
    try:
        # Input city name
        city = input("Enter your city name: ")
        current_weather = get_current_weather(city)

        # Load historical data
        historical_data = read_historical_data('weatherdataset.csv')

        # Prepare and train the rain prediction model
        X, y, le_wind = prepare_data(historical_data)
        rain_model = train_rain_model(X, y)

        # Map wind direction to compass point
        wind_deg = current_weather["wind_deg"] % 360
        compass_points = [
            ("N", 0, 11.25), ("NNE", 11.25, 33.75), ("NE", 33.75, 56.25),
            ("ENE", 56.25, 78.75), ("E", 78.75, 101.25), ("ESE", 101.25, 123.75),
            ("SE", 123.75, 146.25), ("SSE", 146.25, 168.75), ("S", 168.75, 191.25),
            ("SSW", 191.25, 213.75), ("SW", 213.75, 236.25), ("WSW", 236.25, 258.75),
            ("W", 258.75, 281.25), ("WNW", 281.25, 303.75), ("NW", 303.75, 326.25),
            ("NNW", 326.25, 348.75)
        ]

        compass_direction = next(
            (point for point, start, end in compass_points if start <= wind_deg < end),
            None
        )

        if compass_direction and compass_direction in le_wind.classes_:
            compass_direction_encoded = le_wind.transform([compass_direction])[0]
        else:
            compass_direction_encoded = -1  # Default value for unknown directions

        # Prepare current weather data for prediction
        current_data = {
            'MinTemp': float(current_weather['temp_min']),
            'MaxTemp': float(current_weather['temp_max']),
            'WindGustDir': compass_direction_encoded,
            'WindGustSpeed': float(current_weather['Wind_Gust_Speed']),
            'Humidity': float(current_weather['humidity']),
            'Pressure': float(current_weather['pressure']),
            'Temp': float(current_weather['current_temp'])
        }

        current_df = pd.DataFrame([current_data])

        # Rain prediction
        rain_prediction = rain_model.predict(current_df)[0]

        # Prepare regression models for temperature and humidity
        X_temp, y_temp = prepare_regression_data(historical_data, 'Temp')
        X_hum, y_hum = prepare_regression_data(historical_data, 'Humidity')
        temp_model = train_regression_model(X_temp, y_temp)
        hum_model = train_regression_model(X_hum, y_hum)

        # Predict future temperature and humidity
        future_temp = predict_future(temp_model, float(current_weather['temp_min']))
        future_hum = predict_future(hum_model, float(current_weather['humidity']))

        # Prepare times for future predictions
        timezone = pytz.timezone('Asia/Karachi')
        now = datetime.now(timezone)
        next_hour = now + timedelta(hours=1)
        next_hour = next_hour.replace(minute=0, second=0, microsecond=0)
        future_times = [(next_hour + timedelta(hours=i)).strftime("%H:00") for i in range(5)]

        # Display results
        print(f"City: {city}, {current_weather['country']}")
        print(f"Current Temperature: {current_weather['current_temp']}°C")
        print(f"Feels Like: {current_weather['feels_like']}°C")
        print(f"Minimum Temperature: {current_weather['temp_min']}°C")
        print(f"Maximum Temperature: {current_weather['temp_max']}°C")
        print(f"Humidity: {current_weather['humidity']}%")
        print(f"Weather Prediction: {current_weather['description']}")
        print(f"Rain Prediction: {'Yes' if rain_prediction else 'No'}")

        print("\nFuture Temperature Predictions:")
        for time, temp in zip(future_times, future_temp):
            print(f"{time}: {round(temp, 1)}°C")

        print("\nFuture Humidity Predictions:")
        for time, humidity in zip(future_times, future_hum):
            print(f"{time}: {round(humidity, 1)}%")

    except ValueError as ve:
        print(f"Data conversion error: {ve}")
    except Exception as e:
        print(f"An error occurred: {e}")


weather_view()